name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-10.15

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Install SoftHSM
        run: |
          brew install softhsm
          softhsm2-util --init-token --so-pin "12345" --pin "12345" --slot 0 --label "My slot 0"

      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: npm run lint

      - name: Run test with coverage
        run: npm run coverage

      # Fixes problem with incorrect SF paths. See https://github.com/coverallsapp/github-action/issues/125
      - name: Update lcov.info
        run: |
          sed -E "s/SF:(.+file:(.+))/SF:\2/g" ./coverage/lcov.info > coverage/lcov.new.info
          mv ./coverage/lcov.new.info ./coverage/lcov.info

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
