name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      SOFTHSM2_CONF: /etc/softhsm2.conf

    steps:
      - name: Setup Soft HSM
        run: |
          sudo apt-get update -y
          sudo apt-get install -y softhsm2
          echo "SoftHSM2 is installed"
          # Create a configuration file
          echo "directories.tokendir = ${{ github.workspace }}/token" > softhsm2.conf
          echo "objectstore.backend = file" >> softhsm2.conf
          echo "log.level = ERROR" >> softhsm2.conf
          echo "slots.removable = false" >> softhsm2.conf
          echo "slots.mechanisms = ALL" >> softhsm2.conf
          echo "library.reset_on_fork = false" >> softhsm2.conf
          # Create a directory for the token
          mkdir -p ${{ github.workspace }}/token
          # Create a symlink to the SoftHSM library
          softhsm2-util --init-token --so-pin "12345" --pin "12345" --slot 0 --label "My slot 0"
        env:
          SOFTHSM2_CONF: ${{ github.workspace }}/softhsm2.conf

      - name: Install PCSC
        run: sudo apt-get install libpcsclite1 libpcsclite-dev

      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: restore lerna
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: npm run lint

      - name: Run test with coverage
        run: npm run coverage
        env:
          SOFT_HSM_LIBRARY: "/usr/lib/softhsm/libsofthsm2.so"
          SOFTHSM2_CONF: ${{ github.workspace }}/softhsm2.conf

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}