name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      SOFTHSM2_CONF: /etc/softhsm2.conf

    steps:
      - name: Install SoftHSM
        run: |
          sudo apt-get update
          sudo apt-get install -y softhsm2
          # check if softhsm2.conf exists
          if [ ! -f /etc/softhsm2.conf ]; then
            # if not, create it
            sudo touch /etc/softhsm2.conf
            # and add the content
            echo "directories.tokendir = /var/lib/softhsm/slots/" | sudo tee -a /etc/softhsm2.conf
            echo "objectstore.backend = file" | sudo tee -a /etc/softhsm2.conf
            echo "log.level = DEBUG" | sudo tee -a /etc/softhsm2.conf
          fi
          # ensure the directory exists
          sudo mkdir -p /var/lib/softhsm/slots/
          # ensure the file has the correct permissions
          sudo chmod 644 /etc/softhsm2.conf
          softhsm2-util --init-token --so-pin "12345" --pin "12345" --slot 0 --label "My slot 0"

      - name: Install PCSC
        run: sudo apt-get install libpcsclite1 libpcsclite-dev

      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: restore lerna
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: npm run lint

      - name: Run test with coverage
        run: npm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}